webtekno/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using webtekno.Models.entity2;



namespace webtekno.Controllers
{
    [AllowAnonymous]
    public class SecurityController : Controller
    {

        hastadb2Entities3 db = new hastadb2Entities3();
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(sifreler user)
        {
            
            var userIndb = db.sifreler.FirstOrDefault(x => x.kullaniciadi == user.kullaniciadi && x.sifre == user.sifre);
            
             
            if (userIndb == null )
            {
                ViewBag.Mesaj = "Gecersiz Kullanıcı.Kullanıcı adı veya şifre hatalı.";
                FormsAuthentication.SetAuthCookie(user.kullaniciadi, false);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Mesaj = "Gecersiz Kullanıcı.Kullanıcı adı veya şifre hatalı.";
                return View();
            }
            
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        [HttpPost]
        public ActionResult Register(sifreler user)
        {
            db.sifreler.Add(user);
            db.SaveChanges();
            return View();
        }
        
        public ActionResult Register()
        {
            return View();
        }

    }

}

webtekno/Views/Security/Login.cshtml
@using webtekno.Models.entity2
@using System.Web.Mvc.Html
@using System.Web.Mvc
@using System.Web.Optimization
@using System.Web.WebPages.Html

@{
    ViewBag.Title = "Login";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center align-items-center" style="height:100vh">
            <div class="col-4">
                <div class="card">
                    <div class="card-body">
                        <h2> Giriş Formu</h2>

                        @using (Html.BeginForm("Login", "Security", FormMethod.Post))
                        {
                            <div class="form-group">
                                <input name="userName" type="text" placeholder="Kullanıcı Adı" class="form-control">
                            </div>
                            <div class="form-group">
                                <input name="password" type="password" placeholder="Parola" class="form-control">
                            </div>
                            <input type="submit" class="btn btn-primary" value="Login">

                        }
                        <p>
                            <a href="Register" class="btn btn-danger">Kayıt Ol</a>
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

webtekno/Views/Security/Register.cshtml
@{
    ViewBag.Title = "Register";
}
<!DOCTYPE html>
<html>
<form class="form-group" method="post">
    <div>
        <label>Yeni Kullanıcı adınız :</label>
        <input type=" text" class="form-control" name="hastano" />
        <label>Yeni Şifreniz :</label>
        <input type=" text" class="form-control" name="hastaad" />


    </div>
    <div>
        <button class=" btn btn-info"> Kaydet </button>
    </div>

</form>
</html>